import Head from 'next/head';
import Image from 'next/image';
import styles from '@styles/Home.module.css';
import Jumbotron from '@src/components/pages/Home/Jumbotron';
import CryptoLive from '@src/components/pages/Home/CryptoLive';
import Services from '@src/components/pages/Home/Services';
import Payment from '@src/components/pages/Home/Payment';

export default function Home() {
  return (
    <>
      <Head>
        <title>Crt | Home</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Jumbotron />
        <CryptoLive />
        <Services />
        <Payment />
      </main>
    </>
  );
}
